[workspace]
members  = ["crates/*"]
resolver = "2"

[workspace.package]
authors    = ["Aftermath Finance <admin@aftermath.finance>"]
categories = ["cryptography::cryptocurrencies"]
edition    = "2021"
license    = "Apache-2.0"
repository = "https://github.com/AftermathFinance/aftermath-sdk-rust"

[workspace.lints.clippy]
nursery     = { level = "warn", priority = 1 }
todo        = "warn"
unwrap_used = "warn"

# https://github.com/eyre-rs/color-eyre?tab=readme-ov-file#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
