name: CD # Continuous Deployment

on:
  push:
    tags:
      - '*[v]?[0-9]+.[0-9]+.[0-9]+'

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
    with:
      check-all: true

  publish-cargo:
    name: Publishing to Cargo
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-ws"
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo install --locked cargo-workspaces
          cargo ws publish --publish-as-is
